# Approver & pin
APPROVER_EMAIL = "6601983@rungta.org"
APPROVER_PIN   = "4321"                   # approver-only PIN

# SMTP (Gmail example)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"                         # 465 = SSL, 587 = STARTTLS
SMTP_USER = "6601983@rungta.org"
SMTP_PASS = "Ritik@1@2@3"           # Gmail App Password (not your normal password)
SMTP_FROM = "roritik9@gmail.com"         # From address
SMTP_FROM_NAME = "Omega Financial"        # Optional friendly name
